/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VIEWS;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author filip
 */
public class PaginaDialogo extends javax.swing.JDialog {

    private final Color COR_NORMAL_TOP = new Color(97, 99, 103);
    private final Color COR_HOVER = new Color(131, 136, 141);
    private final Color COR_HOVER_FECHAR = new Color(193, 18, 31);
    private final Color COR_ENTRAR_NORMAL = new Color(51, 121, 232);
    private final Color COR_ENTRAR_HOVER = new Color(96, 150, 237);
    private final Color COR_ENTRAR_SELECIONADO = new Color(66, 106, 169);
    
    public PaginaDialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPagina = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        panelFechar = new javax.swing.JPanel();
        labelFechar = new javax.swing.JLabel();
        labelMensagemTop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelBotaoOK = new javax.swing.JPanel();
        labelBotaoOK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 254));
        setMinimumSize(new java.awt.Dimension(500, 254));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 254));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPagina.setBackground(new java.awt.Color(255, 255, 255));

        panelTop.setBackground(new java.awt.Color(97, 99, 103));
        panelTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelTopMouseDragged(evt);
            }
        });
        panelTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelTopMousePressed(evt);
            }
        });

        panelFechar.setBackground(new java.awt.Color(97, 99, 103));
        panelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelFecharMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelFecharMouseReleased(evt);
            }
        });
        panelFechar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFechar.setIcon(new javax.swing.ImageIcon("src/main/java/Recursos/fechar_b.png"));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharpanelFecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelFecharpanelFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelFecharpanelFecharMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelFecharpanelFecharMouseReleased(evt);
            }
        });
        panelFechar.add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 20, 20));

        labelMensagemTop.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelMensagemTop.setForeground(new java.awt.Color(255, 255, 255));
        labelMensagemTop.setText("ERRO");
        labelMensagemTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelMensagemToppanelTopMouseDragged(evt);
            }
        });
        labelMensagemTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelMensagemToppanelTopMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelMensagemTop, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMensagemTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        panelBotaoOK.setBackground(new java.awt.Color(51, 121, 232));
        panelBotaoOK.setPreferredSize(new java.awt.Dimension(174, 48));
        panelBotaoOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBotaoOKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBotaoOKMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBotaoOKMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelBotaoOKMouseReleased(evt);
            }
        });

        labelBotaoOK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelBotaoOK.setForeground(new java.awt.Color(255, 255, 255));
        labelBotaoOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBotaoOK.setText("OK");
        labelBotaoOK.setToolTipText("");
        labelBotaoOK.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelBotaoOKpanelTopMouseDragged(evt);
            }
        });
        labelBotaoOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelBotaoOKpanelBotaoEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelBotaoOKpanelBotaoEntrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelBotaoOKpanelTopMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelBotaoOKpanelBotaoEntrarMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelBotaoOKLayout = new javax.swing.GroupLayout(panelBotaoOK);
        panelBotaoOK.setLayout(panelBotaoOKLayout);
        panelBotaoOKLayout.setHorizontalGroup(
            panelBotaoOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBotaoOK, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        panelBotaoOKLayout.setVerticalGroup(
            panelBotaoOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotaoOKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBotaoOK, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPaginaLayout = new javax.swing.GroupLayout(panelPagina);
        panelPagina.setLayout(panelPaginaLayout);
        panelPaginaLayout.setHorizontalGroup(
            panelPaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPaginaLayout.createSequentialGroup()
                .addGroup(panelPaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPaginaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPaginaLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(panelBotaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelPaginaLayout.setVerticalGroup(
            panelPaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaginaLayout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(panelBotaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        getContentPane().add(panelPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 498, 252));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelFecharpanelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharpanelFecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelFecharpanelFecharMouseClicked

    private void labelFecharpanelFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharpanelFecharMouseEntered
        panelFechar.setBackground(COR_HOVER_FECHAR);
        labelFechar.setIcon(new ImageIcon("src/main/java/Recursos/fechar_b.png"));
    }//GEN-LAST:event_labelFecharpanelFecharMouseEntered

    private void labelFecharpanelFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharpanelFecharMouseExited
        panelFechar.setBackground(COR_NORMAL_TOP);
        labelFechar.setIcon(new ImageIcon("src/main/java/Recursos/fechar.png"));
    }//GEN-LAST:event_labelFecharpanelFecharMouseExited

    private void labelFecharpanelFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharpanelFecharMouseReleased

    }//GEN-LAST:event_labelFecharpanelFecharMouseReleased

    private void panelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_panelFecharMouseClicked

    private void panelFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFecharMouseEntered
        panelFechar.setBackground(COR_HOVER_FECHAR);
    }//GEN-LAST:event_panelFecharMouseEntered

    private void panelFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFecharMouseExited
        panelFechar.setBackground(COR_NORMAL_TOP);
    }//GEN-LAST:event_panelFecharMouseExited

    private void panelFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFecharMouseReleased

    }//GEN-LAST:event_panelFecharMouseReleased

    private void labelMensagemToppanelTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMensagemToppanelTopMouseDragged

    }//GEN-LAST:event_labelMensagemToppanelTopMouseDragged

    private void labelMensagemToppanelTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMensagemToppanelTopMousePressed

    }//GEN-LAST:event_labelMensagemToppanelTopMousePressed

    private void panelTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTopMouseDragged

    }//GEN-LAST:event_panelTopMouseDragged

    private void panelTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTopMousePressed

    }//GEN-LAST:event_panelTopMousePressed

    private void labelBotaoOKpanelTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotaoOKpanelTopMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_labelBotaoOKpanelTopMouseDragged

    private void labelBotaoOKpanelBotaoEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotaoOKpanelBotaoEntrarMouseEntered
        panelBotaoOK.setBackground(COR_ENTRAR_HOVER);
    }//GEN-LAST:event_labelBotaoOKpanelBotaoEntrarMouseEntered

    private void labelBotaoOKpanelBotaoEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotaoOKpanelBotaoEntrarMouseExited
        panelBotaoOK.setBackground(COR_ENTRAR_NORMAL);
    }//GEN-LAST:event_labelBotaoOKpanelBotaoEntrarMouseExited

    private void labelBotaoOKpanelTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotaoOKpanelTopMousePressed
        panelBotaoOK.setBackground(COR_ENTRAR_SELECIONADO);
    }//GEN-LAST:event_labelBotaoOKpanelTopMousePressed

    private void labelBotaoOKpanelBotaoEntrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotaoOKpanelBotaoEntrarMouseReleased
        panelBotaoOK.setBackground(COR_ENTRAR_HOVER);
    }//GEN-LAST:event_labelBotaoOKpanelBotaoEntrarMouseReleased

    private void panelBotaoOKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotaoOKMouseEntered
        panelBotaoOK.setBackground(COR_ENTRAR_HOVER);
    }//GEN-LAST:event_panelBotaoOKMouseEntered

    private void panelBotaoOKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotaoOKMouseExited
        panelBotaoOK.setBackground(COR_ENTRAR_NORMAL);
    }//GEN-LAST:event_panelBotaoOKMouseExited

    private void panelBotaoOKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotaoOKMousePressed
        System.exit(0);
    }//GEN-LAST:event_panelBotaoOKMousePressed

    private void panelBotaoOKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBotaoOKMouseReleased
        if (panelBotaoEntrar.getBounds().contains(evt.getPoint())) {
            panelBotaoEntrar.setBackground(COR_ENTRAR_HOVER);
        } else {
            panelBotaoEntrar.setBackground(COR_ENTRAR_NORMAL);
        }
    }//GEN-LAST:event_panelBotaoOKMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaginaDialogo dialog = new PaginaDialogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelBotaoEntrar;
    private javax.swing.JLabel labelBotaoOK;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelMensagemTop;
    private javax.swing.JPanel panelBotaoEntrar;
    private javax.swing.JPanel panelBotaoOK;
    private javax.swing.JPanel panelFechar;
    private javax.swing.JPanel panelPagina;
    private javax.swing.JPanel panelTop;
    // End of variables declaration//GEN-END:variables
}
