/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEWS;

import CONTROLLERS.HomeController;
import MODELS.CLASS.Cliente;
import MODELS.CLASS.Espaco;
import MODELS.CLASS.Evento;
import MODELS.CLASS.Lugar;
import java.util.List;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author gonca
 */
public class PanelBilheteria extends javax.swing.JPanel {

    /**
     * Creates new form panelBilheteria
     */
    private HomeController controller;
    private PaginaInicial janelaPrincipal;
    private String top, mensagem, imagem;
    java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);

    public PanelBilheteria(PaginaInicial paginaInicial) {
        this.janelaPrincipal = paginaInicial;
        this.controller = new HomeController();
        initComponents();
        carregarDados();
        configurarListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboEvento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboLugares = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        comboCliente = new javax.swing.JComboBox<>();
        btnAdicionarCliente = new javax.swing.JButton();
        btnEmitir = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 235, 238));
        setFocusCycleRoot(true);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("1. Seleção do Evento"));

        jLabel1.setText("Evento:");

        jLabel2.setText("Preço:");

        txtPreco.setEditable(false);
        txtPreco.setText("0.00€");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 780, 120));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("2. Escolha do lugar"));

        jLabel3.setText("Lugares Disponiveis:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(comboLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 780, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("3. Dados do Cliente"));

        btnAdicionarCliente.setBackground(new java.awt.Color(51, 121, 232));
        btnAdicionarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarCliente.setText("Adicionar Cliente");
        btnAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 780, 170));

        btnEmitir.setBackground(new java.awt.Color(51, 121, 232));
        btnEmitir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmitir.setForeground(new java.awt.Color(255, 255, 255));
        btnEmitir.setText("Emitir Bilhete");
        btnEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirActionPerformed(evt);
            }
        });
        add(btnEmitir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarClienteActionPerformed
        if (janelaPrincipal != null) {
            janelaPrincipal.irParaFormularioCliente();
        }
    }//GEN-LAST:event_btnAdicionarClienteActionPerformed

    private void btnEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirActionPerformed

        try {
            Evento eventoSelecionado = (Evento) comboEvento.getSelectedItem();
            Lugar lugarSelecionado = (Lugar) comboLugares.getSelectedItem();
            Cliente clienteSelecionado = (Cliente) comboCliente.getSelectedItem();

            if (eventoSelecionado == null || lugarSelecionado == null || clienteSelecionado == null) {

                PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);

                mensagem = "Por favor, selecione Evento, Cliente e Lugar.";
                top = "Erro";
                imagem = "src/main/java/Recursos/erro.png";

                dialogo.setMensagem(mensagem, top, imagem);
                dialogo.setLocationRelativeTo(win);
                dialogo.setVisible(true);
                return;
            }

            int idEvento = eventoSelecionado.getIdEvento();
            int idLugar = lugarSelecionado.getIdLugar();
            int idCliente = clienteSelecionado.getIdCliente();

            String textoRaw = txtPreco.getText();
            String textoPreco = textoRaw.replace("€", "")
                    .replace(" ", "")
                    .replace(",", ".")
                    .trim();
            double preco = Double.parseDouble(textoPreco);
            long idGerado = controller.efetuarVenda(idLugar, idCliente, idEvento, preco);

            if (idGerado > 0) {
                PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);

                mensagem = "Bilhete criado com sucesso.";
                top = "Aviso";
                imagem = "src/main/java/Recursos/aviso.png";

                dialogo.setMensagem(mensagem, top, imagem);
                dialogo.setLocationRelativeTo(win);
                dialogo.setVisible(true);
                
                carregarDados();
            } else {
                PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);

                mensagem = "Erro ao guardar o bilhete na base de dados.";
                top = "Erro";
                imagem = "src/main/java/Recursos/erro.png";

                dialogo.setMensagem(mensagem, top, imagem);
                dialogo.setLocationRelativeTo(win);
                dialogo.setVisible(true);
            }

        } catch (NumberFormatException e) {
            PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);

            mensagem = "O preço inserido não é válido.";
            top = "Erro";
            imagem = "src/main/java/Recursos/erro.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(win);
            dialogo.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
            PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);

            mensagem = "Ocorreu um erro inesperado.";
            top = "Erro";
            imagem = "src/main/java/Recursos/erro.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(win);
            dialogo.setVisible(true);
        }
    }//GEN-LAST:event_btnEmitirActionPerformed

    private void carregarDados() {
        List<Evento> lista = controller.listarEventosDisponiveis();

        comboEvento.removeAllItems();

        for (Evento ev : lista) {
            comboEvento.addItem(ev);
        }

        Evento ev = (Evento) comboEvento.getSelectedItem();

        comboLugares.removeAllItems();

        if (ev != null) {
            txtPreco.setText(String.valueOf(ev.getPrecoBilhete()) + "€");
            List<Lugar> lista2 = controller.listarLugaresPorSala(ev.getSala(), ev.getIdEvento());

            for (Lugar l : lista2) {
                comboLugares.addItem(l);
            }
        }

        comboCliente.removeAllItems();

        List<Cliente> lista3 = controller.listarTodosClientes();

        for (Cliente c : lista3) {
            comboCliente.addItem(c);
        }

    }

    private void atualizarComboLugares() {
        Evento ev = (Evento) comboEvento.getSelectedItem();

        txtPreco.setText(String.valueOf(ev.getPrecoBilhete()) + "€");

        comboLugares.removeAllItems();

        if (ev != null) {
            List<Lugar> lista2 = controller.listarLugaresPorSala(ev.getSala(), ev.getIdEvento());

            for (Lugar l : lista2) {
                comboLugares.addItem(l);
            }
        }
    }

    private void configurarListeners() {
        comboEvento.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLugares.removeAllItems();
                atualizarComboLugares();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCliente;
    private javax.swing.JButton btnEmitir;
    private javax.swing.JComboBox<Cliente> comboCliente;
    private javax.swing.JComboBox<Evento> comboEvento;
    private javax.swing.JComboBox<Lugar> comboLugares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
