package VIEWS;

import java.awt.Color;

public class PanelSalas extends javax.swing.JPanel {

    private PaginaInicial janelaPrincipal;

    /**
     * Creates new form PanelSalas
     */
    public PanelSalas(PaginaInicial janelaPrincipal) {
        this.janelaPrincipal = janelaPrincipal;
        initComponents();

        btnCriarSala.setVisible(true);
        btnCriarEspaco.setVisible(false);
        btnSalas.setBackground(new Color(51, 121, 232));
        btnSalas.setForeground(new Color(255, 255, 255));
        btnEspacos.setBackground(new Color(255, 255, 255));
        btnEspacos.setForeground(new Color(51, 121, 232));
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaSalas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaEspacos = new javax.swing.JTable();
        btnSalas = new javax.swing.JButton();
        btnEspacos = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnCriarSala = new javax.swing.JButton();
        btnCriarEspaco = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 235, 238));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelaSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tipo", "Capacidade", "Ocupada", "TemLugares", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaSalas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 690, 350));

        TabelaEspacos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelaEspacos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 690, 350));

        btnSalas.setBackground(new java.awt.Color(51, 121, 232));
        btnSalas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalas.setForeground(new java.awt.Color(255, 255, 255));
        btnSalas.setText("Salas");
        btnSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalasActionPerformed(evt);
            }
        });
        add(btnSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 150, 40));

        btnEspacos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEspacos.setForeground(new java.awt.Color(51, 121, 232));
        btnEspacos.setText("Espacos");
        btnEspacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspacosActionPerformed(evt);
            }
        });
        add(btnEspacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 150, 40));

        jTextField1.setText("Pesquisar");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 50, 180, 40));

        btnCriarSala.setBackground(new java.awt.Color(51, 121, 232));
        btnCriarSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriarSala.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarSala.setText("Adicionar Sala");
        btnCriarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarSalaActionPerformed(evt);
            }
        });
        add(btnCriarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 150, 40));

        btnCriarEspaco.setBackground(new java.awt.Color(51, 121, 232));
        btnCriarEspaco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriarEspaco.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarEspaco.setText("Adicionar Espaco");
        btnCriarEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEspacoActionPerformed(evt);
            }
        });
        add(btnCriarEspaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 190, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalasActionPerformed
        btnCriarSala.setVisible(true);
        btnCriarEspaco.setVisible(false);
        btnSalas.setBackground(new Color(51, 121, 232));
        btnSalas.setForeground(new Color(255, 255, 255));
        btnEspacos.setBackground(new Color(255, 255, 255));
        btnEspacos.setForeground(new Color(51, 121, 232));
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(false);
    }//GEN-LAST:event_btnSalasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnCriarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarSalaActionPerformed

    private void btnEspacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspacosActionPerformed
        btnCriarSala.setVisible(false);
        btnCriarEspaco.setVisible(true);
        btnSalas.setBackground(new Color(255, 255, 255));
        btnSalas.setForeground(new Color(51, 121, 232));
        btnEspacos.setBackground(new Color(51, 121, 232));
        btnEspacos.setForeground(new Color(255, 255, 255));
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_btnEspacosActionPerformed

    private void btnCriarEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEspacoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarEspacoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaEspacos;
    private javax.swing.JTable TabelaSalas;
    private javax.swing.JButton btnCriarEspaco;
    private javax.swing.JButton btnCriarSala;
    private javax.swing.JButton btnEspacos;
    private javax.swing.JButton btnSalas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
