/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEWS;

import CONTROLLERS.HomeController;
import MODELS.CLASS.Evento;
import MODELS.CLASS.Tarefa;
import VIEWS.PaginaDialogo;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gonca
 */
public class PanelStaff extends javax.swing.JPanel {

    private HomeController controller;
    private PaginaInicial janelaPrincipal;
    private String top, mensagem, imagem;
    private int idTrabalhador;
    java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);

    public PanelStaff(PaginaInicial paginaInicial, int id) {
        this.janelaPrincipal = paginaInicial;
        this.controller = new HomeController();
        this.idTrabalhador = id;
        initComponents();
        carregarDadosTabelaTarefas(id);
    }

    public PanelStaff(PaginaInicial paginaInicial) {
        this.janelaPrincipal = paginaInicial;
        this.controller = new HomeController();
        initComponents();
        
        tabelaTarefas.getTableHeader().setResizingAllowed(false);
        tabelaTarefas.getTableHeader().setReorderingAllowed(false);
        tabelaTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTarefas = new javax.swing.JTable();
        btnConcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(232, 235, 238));

        tabelaTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Tarefa", "Evento", "Titulo", "Descrição", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaTarefas);
        if (tabelaTarefas.getColumnModel().getColumnCount() > 0) {
            tabelaTarefas.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        btnConcluir.setBackground(new java.awt.Color(51, 121, 232));
        btnConcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnConcluir.setText("Concluir Tarefa");
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(51, 121, 232));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Filtrar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Filtrar por estado:");

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Pendente", "Concluído" }));
        comboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        int linha = tabelaTarefas.getSelectedRow();

        if (linha == -1) {
            PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);
            mensagem = "Nenhuma tarefa selecionada";
            top = "Erro";
            imagem = "src/main/java/Recursos/erro.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(win);
            dialogo.setVisible(true);
            return;
        }

        int modelRow = tabelaTarefas.convertRowIndexToModel(linha);
        int idTarefa = Integer.parseInt(tabelaTarefas.getModel().getValueAt(modelRow, 0).toString());

        if (controller.marcarComoConcluida(idTarefa)) {
            Object itemSelecionado = comboFiltro.getSelectedItem();
            if (itemSelecionado != null) {
                String filtro = itemSelecionado.toString();

                if (filtro.equals("Todas")) {
                    carregarDadosTabelaTarefas(idTrabalhador);
                } else if (filtro.equals("Concluído") || filtro.equals("Concluídas")) {
                    carregarDadosTabelaTarefasConcluidas(idTrabalhador);
                } else if (filtro.equals("Pendente") || filtro.equals("Por fazer")) {
                    carregarDadosTabelaTarefasPendentes(idTrabalhador);
                }
            }
        } else {
            PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);
            mensagem = "Erro ao atualizar tarefa.";
            top = "Erro";
            imagem = "src/main/java/Recursos/erro.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(win);
            dialogo.setVisible(true);
        }

    }//GEN-LAST:event_btnConcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String filtro = comboFiltro.getSelectedItem().toString();

        if (filtro.equals("Todas")) {
            carregarDadosTabelaTarefas(idTrabalhador);
        } else if (filtro.equals("Concluído")) {
            carregarDadosTabelaTarefasConcluidas(idTrabalhador);
        } else if (filtro.equals("Pendente")) {
            carregarDadosTabelaTarefasPendentes(idTrabalhador);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void comboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFiltroActionPerformed

    private void carregarDadosTabelaTarefas(int idStaff) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaTarefas.getModel();
        modelo.setRowCount(0);

        List<Tarefa> lista = controller.listarTarefasPorTrabalhador(idStaff);

        for (Tarefa t : lista) {
            String nomeEvento = null;
            int idEvento = t.getEvento();
            Evento evento = controller.buscarEventoPorId(idEvento);

            if (evento != null) {
                nomeEvento = evento.getNome();
            }

            modelo.addRow(new Object[]{
                t.getIdTarefa(),
                nomeEvento,
                t.getTitulo(),
                t.getDescricao(),
                (t.isEstado() == true) ? "Concluída" : "Por fazer"
            });
        }
    }

    private void carregarDadosTabelaTarefasConcluidas(int idStaff) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaTarefas.getModel();
        modelo.setRowCount(0);

        List<Tarefa> lista = controller.listarTarefasConcluidas(idStaff);

        for (Tarefa t : lista) {
            String nomeEvento = null;
            int idEvento = t.getEvento();
            Evento evento = controller.buscarEventoPorId(idEvento);

            if (evento != null) {
                nomeEvento = evento.getNome();
            }

            modelo.addRow(new Object[]{
                t.getIdTarefa(),
                nomeEvento,
                t.getTitulo(),
                t.getDescricao(),
                (t.isEstado() == true) ? "Concluída" : "Por fazer"
            });
        }
    }

    private void carregarDadosTabelaTarefasPendentes(int idStaff) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaTarefas.getModel();
        modelo.setRowCount(0);

        List<Tarefa> lista = controller.listarTarefasPendentes(idStaff);

        for (Tarefa t : lista) {
            String nomeEvento = null;
            int idEvento = t.getEvento();
            Evento evento = controller.buscarEventoPorId(idEvento);

            if (evento != null) {
                nomeEvento = evento.getNome();
            }

            modelo.addRow(new Object[]{
                t.getIdTarefa(),
                nomeEvento,
                t.getTitulo(),
                t.getDescricao(),
                (t.isEstado() == true) ? "Concluída" : "Por fazer"
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnConcluir;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTarefas;
    // End of variables declaration//GEN-END:variables
}
