package VIEWS;

import CONTROLLERS.HomeController;
import MODELS.CLASS.Evento;
import MODELS.CLASS.Sala;
import MODELS.CLASS.Trabalhador;
import java.awt.Color;
import java.awt.event.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class PanelEventos extends javax.swing.JPanel {

    private PaginaInicial janelaPrincipal;
    private HomeController controller;

    public PanelEventos(PaginaInicial paginaInicial) {
        this.janelaPrincipal = paginaInicial;
        this.controller = new HomeController();
        initComponents();
        
        configurarPesquisa();
        carregarTabela(null);
    }
    
    // --- PESQUISA ---
    private void configurarPesquisa() {
        txtPesquisar.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e) {
                if (txtPesquisar.getText().equals("Pesquisar")) {
                    txtPesquisar.setText("");
                    txtPesquisar.setForeground(Color.BLACK);
                }
            }
            public void focusLost(FocusEvent e) {
                if (txtPesquisar.getText().isEmpty()) {
                    txtPesquisar.setText("Pesquisar");
                    txtPesquisar.setForeground(new Color(153, 153, 153));
                }
            }
        });
        
        txtPesquisar.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                String termo = txtPesquisar.getText().trim();
                if(termo.equals("Pesquisar")) termo = "";
                
                if(termo.isEmpty()) {
                    carregarTabela(null);
                } else {
                    carregarTabela(controller.pesquisarEventos(termo));
                }
            }
        });
    }
    
    // --- CARREGAR TABELA OTIMIZADO (SEM LENTIDÃO) ---
    private void carregarTabela(List<Evento> listaParaMostrar) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaEventos.getModel();
        modelo.setRowCount(0);
        
        List<Evento> listaEventos = (listaParaMostrar != null) ? listaParaMostrar : controller.obterTodosEventos();
        List<Trabalhador> todosTrabs = controller.obterTodosFuncionarios();
        List<Sala> todasSalas = controller.listarTodasSalasAtivas();
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        
        for (Evento e : listaEventos) {
            String nomeResp = "N/A";
            for(Trabalhador t : todosTrabs) {
                if(t.getIdTrabalhador() == e.getResponsavel()) { nomeResp = t.getNome(); break; }
            }
            
            String nomeSala = "N/A";
            for(Sala s : todasSalas) {
                if(s.getIdSala() == e.getSala()) { nomeSala = s.getNome(); break; }
            }
            
            String dataStr = (e.getData() != null) ? sdf.format(e.getData()) : "";

            modelo.addRow(new Object[]{
                e.getIdEvento(),
                e.getNome(),
                dataStr,
                e.getDescricao(),
                nomeResp,
                nomeSala,
                e.getHora(),
                e.isEstado()
            });
        }
    }
    
    // --- POP-UP ---
    private void mostrarAviso(String msg, String titulo, String img) {
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        PaginaDialogo d = new PaginaDialogo(parent, true);
        d.setMensagem(msg, titulo, img);
        d.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEventos = new javax.swing.JTable();
        btnCriar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 235, 238));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPesquisar.setText("Pesquisar");
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 50, 180, 40));

        tabelaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Data", "Descrição", "Responsável", "Sala", "Hora", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaEventos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 108, 690, 350));

        btnCriar.setBackground(new java.awt.Color(51, 121, 232));
        btnCriar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriar.setForeground(new java.awt.Color(255, 255, 255));
        btnCriar.setText("Adicionar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        add(btnCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 488, 150, 40));

        btnEditar.setBackground(new java.awt.Color(51, 121, 232));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 488, 150, 40));

        btnEditar1.setBackground(new java.awt.Color(51, 121, 232));
        btnEditar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar1.setText("Eliminar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 488, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:String nome = txtNome.getText();
        /*String nome = txtNome1.getText();
        String emailP = txtEmailP1.getText();
        String emailT = txtEmailT1.getText();
        String categoria = cbCategoria.getSelectedItem().toString();
        String password = txtPassword.getText();
        boolean atividade = chkAtividade.isSelected();

        CONTROLLERS.HomeController.criarTrabalhador(
            nome, emailP, emailT, categoria, password, atividade
        );*/

        //dispose();
        
        if(janelaPrincipal != null){
            janelaPrincipal.irParaFormularioEventos();
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linhaSelecionada = tabelaEventos.getSelectedRow();

        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um funcionário na tabela pra editar.");
            return;
        }

        //Obtem os dados da tabela
        String id = tabelaEventos.getValueAt(linhaSelecionada, 0).toString();
        String nome = tabelaEventos.getValueAt(linhaSelecionada, 1).toString();
        String email = tabelaEventos.getValueAt(linhaSelecionada, 2).toString();
        String categoria = tabelaEventos.getValueAt(linhaSelecionada, 3).toString();

        if (janelaPrincipal != null) {
            janelaPrincipal.irParaEditarFuncionario(id, nome, email, categoria);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEventos;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
