package VIEWS;

import CONTROLLERS.HomeController;
import MODELS.CLASS.Espaco;
import MODELS.CLASS.Sala;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PanelSalas extends javax.swing.JPanel {

    private PaginaInicial janelaPrincipal;
    private HomeController controller;
    private String top, mensagem, imagem;
    java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);

    /**
     * Creates new form PanelSalas
     */
    public PanelSalas(PaginaInicial janelaPrincipal) {
        this.janelaPrincipal = janelaPrincipal;
        this.controller = new HomeController();
        initComponents();
        carregarDadosTabelaEspacos();
        carregarDadosTabelaSalas();
        btnCriarSala.setVisible(true);
        btnCriarEspaco.setVisible(false);
        btnEditarSala.setVisible(true);
        btnEditarEspaco.setVisible(false);
        btnSalas.setBackground(new Color(51, 121, 232));
        btnSalas.setForeground(new Color(255, 255, 255));
        btnEspacos.setBackground(new Color(255, 255, 255));
        btnEspacos.setForeground(new Color(51, 121, 232));
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaSalas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaEspacos = new javax.swing.JTable();
        btnSalas = new javax.swing.JButton();
        btnEspacos = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnCriarSala = new javax.swing.JButton();
        btnCriarEspaco = new javax.swing.JButton();
        btnDesativarSala = new javax.swing.JButton();
        btnEditarSala = new javax.swing.JButton();
        btnEditarEspaco = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 235, 238));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelaSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tipo", "Capacidade", "Ocupação", "TemLugares"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaSalas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 690, 350));

        TabelaEspacos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelaEspacos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 690, 350));

        btnSalas.setBackground(new java.awt.Color(51, 121, 232));
        btnSalas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalas.setForeground(new java.awt.Color(255, 255, 255));
        btnSalas.setText("Salas");
        btnSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalasActionPerformed(evt);
            }
        });
        add(btnSalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 150, 40));

        btnEspacos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEspacos.setForeground(new java.awt.Color(51, 121, 232));
        btnEspacos.setText("Espacos");
        btnEspacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspacosActionPerformed(evt);
            }
        });
        add(btnEspacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 150, 40));

        jTextField1.setText("Pesquisar");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 50, 180, 40));

        btnCriarSala.setBackground(new java.awt.Color(51, 121, 232));
        btnCriarSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriarSala.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarSala.setText("Adicionar Sala");
        btnCriarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarSalaActionPerformed(evt);
            }
        });
        add(btnCriarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 150, 40));

        btnCriarEspaco.setBackground(new java.awt.Color(51, 121, 232));
        btnCriarEspaco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriarEspaco.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarEspaco.setText("Adicionar Espaco");
        btnCriarEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarEspacoActionPerformed(evt);
            }
        });
        add(btnCriarEspaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 190, 40));

        btnDesativarSala.setBackground(new java.awt.Color(51, 121, 232));
        btnDesativarSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDesativarSala.setForeground(new java.awt.Color(255, 255, 255));
        btnDesativarSala.setText("Desativar Sala");
        btnDesativarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesativarSalaActionPerformed(evt);
            }
        });
        add(btnDesativarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 150, 40));

        btnEditarSala.setBackground(new java.awt.Color(51, 121, 232));
        btnEditarSala.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarSala.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarSala.setText("Editar Sala");
        btnEditarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSalaActionPerformed(evt);
            }
        });
        add(btnEditarSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 150, 40));

        btnEditarEspaco.setBackground(new java.awt.Color(51, 121, 232));
        btnEditarEspaco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarEspaco.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEspaco.setText("Editar Espaco");
        btnEditarEspaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEspacoActionPerformed(evt);
            }
        });
        add(btnEditarEspaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 190, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalasActionPerformed
        btnCriarSala.setVisible(true);
        btnCriarEspaco.setVisible(false);
        btnEditarSala.setVisible(true);
        btnEditarEspaco.setVisible(false);
        btnSalas.setBackground(new Color(51, 121, 232));
        btnSalas.setForeground(new Color(255, 255, 255));
        btnEspacos.setBackground(new Color(255, 255, 255));
        btnEspacos.setForeground(new Color(51, 121, 232));
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(false);
    }//GEN-LAST:event_btnSalasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnCriarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarSalaActionPerformed
        if (janelaPrincipal != null) {
            janelaPrincipal.irParaFormularioSalas();
        }
    }//GEN-LAST:event_btnCriarSalaActionPerformed

    private void btnEspacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspacosActionPerformed
        btnCriarSala.setVisible(false);
        btnCriarEspaco.setVisible(true);
        btnEditarSala.setVisible(false);
        btnEditarEspaco.setVisible(true);
        btnSalas.setBackground(new Color(255, 255, 255));
        btnSalas.setForeground(new Color(51, 121, 232));
        btnEspacos.setBackground(new Color(51, 121, 232));
        btnEspacos.setForeground(new Color(255, 255, 255));
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_btnEspacosActionPerformed

    private void btnCriarEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEspacoActionPerformed
        if (janelaPrincipal != null) {
            janelaPrincipal.irParaFormularioEspacos();
        }
    }//GEN-LAST:event_btnCriarEspacoActionPerformed

    private void btnEditarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSalaActionPerformed
        PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);
        int linhaSelecionada = TabelaSalas.getSelectedRow();

        if (linhaSelecionada == -1) {
            mensagem = "Nenhuma sala selecionada";
            top = "Erro";
            imagem = "src/main/java/Recursos/erro.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(win);
            dialogo.setVisible(true);
            return;
        }

        int modelRow = TabelaSalas.convertRowIndexToModel(linhaSelecionada);

        Object valorId = TabelaSalas.getModel().getValueAt(modelRow, 0);

        int idSala = (int) valorId;

        if (janelaPrincipal != null) {
            janelaPrincipal.irParaFormularioSalas(idSala);
        }

    }//GEN-LAST:event_btnEditarSalaActionPerformed

    private void btnEditarEspacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEspacoActionPerformed
        PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);
        int linhaSelecionada = TabelaEspacos.getSelectedRow();

        if (linhaSelecionada == -1) {
            mensagem = "Nenhuma sala selecionada";
            top = "Erro";
            imagem = "src/main/java/Recursos/erro.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(win);
            dialogo.setVisible(true);
            return;
        }

        int modelRow = TabelaEspacos.convertRowIndexToModel(linhaSelecionada);

        Object valorId = TabelaEspacos.getModel().getValueAt(modelRow, 0);

        int idEspaco = (int) valorId;

        if (janelaPrincipal != null) {
            janelaPrincipal.irParaFormularioEspacos(idEspaco);
        }
    }//GEN-LAST:event_btnEditarEspacoActionPerformed

    private void btnDesativarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesativarSalaActionPerformed
        PaginaDialogo dialogo = new PaginaDialogo((java.awt.Frame) win, true);
        int linhaSelecionada = TabelaSalas.getSelectedRow();

        if (linhaSelecionada == -1) {
            mensagem = "Nenhuma sala selecionada";
            top = "Erro";
            imagem = "src/main/java/Recursos/erro.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(win);
            dialogo.setVisible(true);
            return;
        }

        int modelRow = TabelaSalas.convertRowIndexToModel(linhaSelecionada);

        Object valorId = TabelaSalas.getModel().getValueAt(modelRow, 0);

        int idSala = (int) valorId;

        if (controller.podeSerEliminada(idSala)) {

            mensagem = "Impossível eliminar: Esta sala possui eventos associados!";
            top = "Bloqueio de Segurança";
            imagem = "src/main/java/Recursos/aviso.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(win);
            dialogo.setVisible(true);
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja desativar esta sala?");
        if (confirmacao == JOptionPane.YES_OPTION) {
            if (controller.eliminarSala(idSala)) {
                carregarDadosTabelaSalas();
            } else {
                mensagem = "Erro ao desativar sala.";
                top = "Erro";
                imagem = "src/main/java/Recursos/aviso.png";

                dialogo.setMensagem(mensagem, top, imagem);
                dialogo.setLocationRelativeTo(win);
                dialogo.setVisible(true);
                return;
            }
        }
    }//GEN-LAST:event_btnDesativarSalaActionPerformed

    private void carregarDadosTabelaEspacos() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaEspacos.getModel();
        modelo.setRowCount(0);

        List<Espaco> lista = controller.obterTodosEspacos();

        for (Espaco e : lista) {
            modelo.addRow(new Object[]{
                e.getIdEspaco(),
                e.getNome()
            });
        }
    }

    private void carregarDadosTabelaSalas() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaSalas.getModel();
        modelo.setRowCount(0);

        List<Sala> lista = controller.listarTodasSalasAtivas();

        for (Sala s : lista) {
            modelo.addRow(new Object[]{
                s.getIdSala(),
                s.getNome(),
                s.getTipoEspaco(),
                s.getLugares(),
                // Se for true aparece "Ocupada", se for false aparece "Livre"
                s.isOcupada() ? "Ocupada" : "Livre",
                // Se for true aparece "Sim", se for false aparece "Não"
                s.isTemLugares() ? "Sim" : "Não"
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaEspacos;
    private javax.swing.JTable TabelaSalas;
    private javax.swing.JButton btnCriarEspaco;
    private javax.swing.JButton btnCriarSala;
    private javax.swing.JButton btnDesativarSala;
    private javax.swing.JButton btnEditarEspaco;
    private javax.swing.JButton btnEditarSala;
    private javax.swing.JButton btnEspacos;
    private javax.swing.JButton btnSalas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
