package VIEWS;

import CONTROLLERS.HomeController;
import MODELS.CLASS.Trabalhador;
import MODELS.CLASS.CategoriaTrabalho;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

public class PanelListaFuncionarios extends javax.swing.JPanel {

    private PaginaInicial janelaPrincipal;
    private HomeController controller;
    private String top, mensagem, imagem;
    private boolean clicouSim;

    public PanelListaFuncionarios(PaginaInicial paginaInicial) {
        this.janelaPrincipal = paginaInicial;
        this.controller = new HomeController();
        initComponents();
        
        tabelaFuncionarios.getTableHeader().setResizingAllowed(false);
        tabelaFuncionarios.getTableHeader().setReorderingAllowed(false);
        tabelaFuncionarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        carregarTabela(null);
        
        txtPesquisar.setText("Pesquisar");
        txtPesquisar.setForeground(java.awt.Color.GRAY);

        txtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtPesquisar.getText().equals("Pesquisar") && txtPesquisar.getForeground().equals(java.awt.Color.GRAY)) {
                    txtPesquisar.setText("");
                    txtPesquisar.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtPesquisar.getText().isEmpty()) {
                    txtPesquisar.setForeground(java.awt.Color.GRAY);
                    txtPesquisar.setText("Pesquisar");
                }
            }
        });
        
        txtPesquisar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { verificarEFiltrar(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { verificarEFiltrar(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { verificarEFiltrar(); }
        });
    }
    
    private void verificarEFiltrar() {
        String termo = txtPesquisar.getText();

        if (txtPesquisar.getForeground().equals(java.awt.Color.GRAY) && termo.equals("Pesquisar")) {
            aplicarFiltro("");
        } else {
            aplicarFiltro(termo);
        }
    }

    private void aplicarFiltro(String termo) {
        DefaultTableModel modF = (DefaultTableModel) tabelaFuncionarios.getModel();
        TableRowSorter<DefaultTableModel> sorterF = new TableRowSorter<>(modF);
        tabelaFuncionarios.setRowSorter(sorterF);

        if (termo.trim().isEmpty()) {
            sorterF.setRowFilter(null);
        } else {
            sorterF.setRowFilter(RowFilter.regexFilter("(?i)" + termo));
        }
    }
    
    private void carregarTabela(List<Trabalhador> listaParaMostrar) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaFuncionarios.getModel();
        modelo.setRowCount(0);
        
        List<Trabalhador> lista;
        if (listaParaMostrar != null) {
            lista = listaParaMostrar;
        } else {
            lista = controller.obterTodosFuncionarios();
        }
        
        List<CategoriaTrabalho> categorias = controller.getCategoriasTrabalho();
        
        for (Trabalhador t : lista) {
            if (t.isAtivo()) {
                String nomeCategoria = "Desconhecida";
                for (CategoriaTrabalho cat : categorias) {
                    if (cat.getIdCategoria() == t.getCategoria()) {
                        nomeCategoria = cat.getNome();
                        break;
                    }
                }
                
                modelo.addRow(new Object[]{
                    t.getIdTrabalhador(),
                    t.getNome(),
                    t.getEmailPessoal(),
                    nomeCategoria
                });
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 235, 238));

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFuncionarios.setShowGrid(false);
        jScrollPane1.setViewportView(tabelaFuncionarios);

        txtPesquisar.setText("Pesquisar");
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        btnCriar.setBackground(new java.awt.Color(51, 121, 232));
        btnCriar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriar.setForeground(new java.awt.Color(255, 255, 255));
        btnCriar.setText("Adicionar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(51, 121, 232));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(51, 121, 232));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        String termo = txtPesquisar.getText().trim();
        if (termo.isEmpty() || termo.equals("Pesquisar")) {
            carregarTabela(null);
        } else {
            List<Trabalhador> resultados = controller.pesquisarFuncionarios(termo);
            carregarTabela(resultados);
        }
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
       if (janelaPrincipal != null) {
            janelaPrincipal.irParaFormularioFuncionarios();
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linhaSelecionada = tabelaFuncionarios.getSelectedRow();
        if (linhaSelecionada == -1) {
            PaginaDialogo dialogo = new PaginaDialogo(janelaPrincipal, true);

            mensagem = "Selecione um funcionário para editar.";
            top = "Atenção";
            imagem = "src/main/java/Recursos/aviso.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(janelaPrincipal);
            dialogo.setVisible(true);
            return;
        }
        
        String id = tabelaFuncionarios.getValueAt(linhaSelecionada, 0).toString();
        String nome = tabelaFuncionarios.getValueAt(linhaSelecionada, 1).toString();
        String email = tabelaFuncionarios.getValueAt(linhaSelecionada, 2).toString();
        String categoria = tabelaFuncionarios.getValueAt(linhaSelecionada, 3).toString();

        if (janelaPrincipal != null) {
            janelaPrincipal.irParaEditarFuncionario(id, nome, email, categoria);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int linhaSelecionada = tabelaFuncionarios.getSelectedRow();
        if (linhaSelecionada == -1) {
            PaginaDialogo dialogo = new PaginaDialogo(janelaPrincipal, true);

            mensagem = "Selecione um funcionário para eliminar.";
            top = "Atenção";
            imagem = "src/main/java/Recursos/aviso.png";

            dialogo.setMensagem(mensagem, top, imagem);
            dialogo.setLocationRelativeTo(janelaPrincipal);
            dialogo.setVisible(true);
            return;
        }

        int id = (int) tabelaFuncionarios.getValueAt(linhaSelecionada, 0);
        String nome = (String) tabelaFuncionarios.getValueAt(linhaSelecionada, 1);

        PaginaOpcao dialog = new PaginaOpcao(janelaPrincipal, true);
        
        top = "Eliminar Funcionário";
        mensagem = "Deseja eliminar o funcionário '" + nome + "'?";
        
        dialog.setMensagem(mensagem, top);
        dialog.setLocationRelativeTo(janelaPrincipal);
        dialog.setVisible(true); 

        if (dialog.clicouSim()) {
            if (controller.eliminarFuncionario(id)) {
                PaginaDialogo dialogo = new PaginaDialogo(janelaPrincipal, true);

                mensagem = "Funcionário '" + nome + "' eliminado com sucesso.";
                top = "Sucesso";
                imagem = "src/main/java/Recursos/info.png";

                dialogo.setMensagem(mensagem, top, imagem);
                dialogo.setLocationRelativeTo(janelaPrincipal);
                dialogo.setVisible(true);
                
                carregarTabela(null); 
            } else {
                PaginaDialogo dialogo = new PaginaDialogo(janelaPrincipal, true);

                mensagem = "Erro ao eliminar funcionário.";
                top = "Erro";
                imagem = "src/main/java/Recursos/erro.png";

                dialogo.setMensagem(mensagem, top, imagem);
                dialogo.setLocationRelativeTo(janelaPrincipal);
                dialogo.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
