/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEWS;

import CONTROLLERS.HomeController;
import MODELS.CLASS.Evento;
import MODELS.CLASS.Recurso;
import MODELS.CLASS.Sala;
import MODELS.CLASS.Trabalhador;
import java.util.List;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author filip
 */
public class PanelAssociarRecurso extends javax.swing.JPanel {

    private PaginaInicial janelaPrincipal;
    private HomeController controller;
    private List<Evento> listaEventos;
    private List<Recurso> listaRecursos;
    /**
     * Creates new form PanelAssociarRecurso
     */
    public PanelAssociarRecurso(PaginaInicial janelaPrincipal) {
        this.janelaPrincipal = janelaPrincipal;
        this.controller = new HomeController();
        initComponents();
        carregarCombos();
        spQuantidade.setModel(new SpinnerNumberModel(0, 0, null, 1));
        
        cbEvento.addActionListener(e -> verificarEPreencherQuantidade());
        cbRecurso.addActionListener(e -> verificarEPreencherQuantidade());
    }
    
    private void carregarCombos() {
    cbEvento.removeAllItems();
    listaEventos = controller.listarTodosEventosAtivos(); 
    
    // Filtrar a lista para remover Cancelados (1) ou Não Ativos (Estado = 0)
    for (Evento e : listaEventos) {
        // Só adiciona se Cancelado for FALSO E Estado for VERDADEIRO (Por decorrer)
        if (!e.isCancelado() && e.isEstado()) {
            cbEvento.addItem(e.getNome());
        }
    }

    cbRecurso.removeAllItems();
    listaRecursos = controller.listarTodosRecursosAtivas(); 
    
    for (Recurso r : listaRecursos) {
        cbRecurso.addItem(r.getNome()); 
    }
}
    
    private void verificarEPreencherQuantidade() {
        int indexEv = cbEvento.getSelectedIndex();
        int indexRec = cbRecurso.getSelectedIndex();

        if (indexEv != -1 && indexRec != -1) {
            int idEvento = listaEventos.get(indexEv).getIdEvento();
            int idRecurso = listaRecursos.get(indexRec).getIdRecurso();

            int qtdAtual = controller.obterQuantidadeRecursoNoEvento(idEvento, idRecurso);
            
            // Se qtdAtual for > 0, significa que já existe na tabela EventoRecurso
            spQuantidade.setValue(qtdAtual); 
        }
    }
    
    // --- POP-UP AUXILIAR ---
    private void mostrarAviso(String msg, String titulo, String img) {
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        PaginaDialogo d = new PaginaDialogo(parent, true);
        d.setMensagem(msg, titulo, img);
        d.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEvento = new javax.swing.JLabel();
        cbEvento = new javax.swing.JComboBox<>();
        cbRecurso = new javax.swing.JComboBox<>();
        lblRecurso = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        spQuantidade = new javax.swing.JSpinner();
        lblRecurso2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(735, 520));
        setPreferredSize(new java.awt.Dimension(735, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEvento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEvento.setText("Evento");
        add(lblEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        cbEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 630, 35));

        cbRecurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 370, 35));

        lblRecurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRecurso.setText("Recurso");
        add(lblRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 150, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 150, 40));
        add(spQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 180, 35));

        lblRecurso2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRecurso2.setText("Quantidade");
        add(lblRecurso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (janelaPrincipal != null) {
            janelaPrincipal.mostrarListaEventos();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            int indexEvento = cbEvento.getSelectedIndex();
            int indexRecurso = cbRecurso.getSelectedIndex();

            if (indexEvento == -1 || indexRecurso == -1) {
                mostrarAviso("Selecione um evento e um recurso.", "Atenção", "src/main/java/Recursos/aviso.png");
                return;
            }

            int idEvento = listaEventos.get(indexEvento).getIdEvento();
            int idRecurso = listaRecursos.get(indexRecurso).getIdRecurso();
            int quantidade = (int) spQuantidade.getValue();

            // REMOVIDA a validação "if (quantidade <= 0)" para permitir o 0

            boolean sucesso = controller.associarRecursoAEvento(idEvento, idRecurso, quantidade);

            if (sucesso) {
                if (quantidade == 0) {
                    mostrarAviso("Associação removida com sucesso!", "Sucesso", "src/main/java/Recursos/info.png");
                } else {
                    mostrarAviso("Dados guardados com sucesso!", "Sucesso", "src/main/java/Recursos/info.png");
                }
            } else {
                mostrarAviso("Não foi possível processar a operação. Verifique o stock disponível.", "Erro", "src/main/java/Recursos/erro.png");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbEvento;
    private javax.swing.JComboBox<String> cbRecurso;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblRecurso;
    private javax.swing.JLabel lblRecurso2;
    private javax.swing.JSpinner spQuantidade;
    // End of variables declaration//GEN-END:variables
}
