/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEWS;

/**
 *
 * @author gonca
 */
public class PanelFormularioEventos extends javax.swing.JPanel {

    private PaginaInicial janelaPrincipal;
    private String top, mensagem, imagem;
    java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);

    /**
     * Creates new form PanelFormularioEventos
     */
    public PanelFormularioEventos(PaginaInicial paginaInicial) {
        this.janelaPrincipal = paginaInicial;
        initComponents();

        configurarRelogio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        comboSala = new javax.swing.JComboBox<>();
        comboResponsavel = new javax.swing.JComboBox<>();
        dateEvento = new com.toedter.calendar.JDateChooser();
        spinHoraInicio = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(232, 235, 238));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID.setText("ID");
        txtID.setEnabled(false);
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 6, -1, 35));

        txtNome.setText("Nome Completo");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 124, 638, 35));

        txtDescricao.setText("Descrição");
        add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 230, 638, 35));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 468, 150, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 468, 150, 40));

        add(comboSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 336, 325, 35));

        comboResponsavel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 283, 325, 35));
        add(dateEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 35));

        spinHoraInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));
        spinHoraInicio.setEditor(new javax.swing.JSpinner.DateEditor(spinHoraInicio, "HH:mm"));
        add(spinHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Apenas pedimos à janela principal para mostrar a lista novamente
        if (janelaPrincipal != null) {
            janelaPrincipal.mostrarListaEventos();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNome.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Falta o nome!");
            return;
        }

        if (dateEvento.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Falta a data!");
            return;
        }

        //Converter Calendário para SQL Date 
        java.sql.Date dataParaEnviar = new java.sql.Date(dateEvento.getDate().getTime());

        //Converter Spinner para SQL Time
        java.util.Date horaCrua = (java.util.Date) spinHoraInicio.getValue();
        java.sql.Time horaParaEnviar = new java.sql.Time(horaCrua.getTime());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void configurarRelogio() {
        javax.swing.JSpinner.DateEditor editor = new javax.swing.JSpinner.DateEditor(spinHoraInicio, "HH:mm");
        spinHoraInicio.setEditor(editor);
        spinHoraInicio.setValue(new java.util.Date()); // Define a hora atual como padrão
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboResponsavel;
    private javax.swing.JComboBox<String> comboSala;
    private com.toedter.calendar.JDateChooser dateEvento;
    private javax.swing.JSpinner spinHoraInicio;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
